### ISSUE TITLE
Add Northstar integration & RBAC

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomething/nightwing#16]
If we want to deploy as a public app, we'll need the same level of auth as for, e.g., Guardian.

**Comment by mshmsh5000** [comment]
(Role-based access control, or whatever level of this we implement for admin access elsewhere.)

**Comment by angaither** [comment]
Blocked by DoSomething/northstar-php/issues/5

**Comment by angaither** [comment]
@katiecrane is going to downgrade the version of guzzle used here to v5, instead of the latest, greatest guzzle.
