### ISSUE TITLE
Pull service key from env vars

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomething/nightwing#18]
https://github.com/DoSomething/nightwing/blob/master/app/Providers/FastlyProvider.php#L32

and elsewhere hard-code the service key. This and the dictionary keys should all come from `.env`.

cc @blisteringherb

**Comment by katiecrane** [comment]
@mshmsh5000 [these three keys](https://github.com/DoSomething/nightwing/blob/master/app/Providers/FastlyProvider.php#L22-L24) here come from [`config/services.php`](https://github.com/DoSomething/nightwing/blob/master/config/services.php#L38-L42) which are pulling from the `.env`, which is I think what we want? Or do we want to pull directly from the `.env` in `FastlyProvider.php`?

**Comment by katiecrane** [comment]
@mshmsh5000 Oh wait! I see there is another key in there too. Yeah we can add that in no problem!

**Comment by mshmsh5000** [comment]
More specifically, right now we're reading these three values from config:

```
$fastly_key = config('services.fastly.key');
$fastly_table_redirects = config('services.fastly.table_redirects');
$fastly_table_redirect_types = config('services.fastly.table_redirect_types');
```

`services.fastly.key` is the secret API key of the Fastly user. We need a fourth value, to be named something like `property` or `config`, which is the key of the Fastly service whose VCL we're altering.
