### ISSUE TITLE
PURGE

### ISSUE THREAD

**Issue by katiecrane** [DoSomething/nightwing#22]
@mshmsh5000 says we should probably add a `PURGE` to the service for updates and deletes.

Currently the tables reflect what we want them to, but fastly caches stuff, so if you delete a redirect it will still work.

https://docs.fastly.com/api/purge

**Comment by mshmsh5000** [comment]
That's true. I said all that.

**Comment by mshmsh5000** [comment]
Specifically: Any CDN will likely cache `301` responses by default. To be safe, we can cheaply issue a `PURGE` for any redirect that we edit or delete.
