### ISSUE TITLE
Manual setup required for dosomething.org deployment

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomething/nightwing#5]
- [x] _Using API calls_, create the two dictionaries in the dosomething.org Fastly config
- [x] Upload Redirect app custom VCL file to dosomething.org Fastly config
- [x]  _For launch:_ Update service & dictionary references in Nightwing

**Comment by blisteringherb** [comment]
Dictionaries created `redirect_types` and `redirects` in version 111 via API.

**Comment by blisteringherb** [comment]
I've activated version 111 with the new dictionaries, custom VCL, and updated the following vars in .env with their production values:

FASTLY_SERVICE_KEY  
FASTLY_TABLE_REDIRECTS  
FASTLY_TABLE_REDIRECT_TYPES  
FASTLY_SERVICE_DOMAIN

@katiecrane @mshmsh5000
